name: github-pages
on:
  push:
    branches:
    - publish
  page_build:
  workflow_dispatch:
jobs:
  install_ts:
    name: Install TypeScript
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/setup-node@v3
    - run: npm install typescript
  compile:
    name: Compile TypeScript files
    needs: [install_ts]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - run: mkdir ./build
    - name: Compile
      run: tsc --project .
    - run: cp parallelogram.html ./build/index.html
  upload:
    name: Upload build artifact
    needs: [compile]
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./build
  deploy:
    name: Deploy to GitHub Pages
    needs: [upload]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
