name: github-pages
on:
  push:
    branches:
    - publish
  page_build:
  workflow_dispatch:
jobs:
  install_typescript:
    name: Install TypeScript
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/setup-node@v3
    - run: npm install typescript
  compile_project:
    name: Compile TypeScript files
    runs-on: ubuntu-latest
    needs: [install_typescript]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - run: mkdir build
    - run: tsc --project .
    - run: cp parallelogram.html build/index.html
