name: github-pages
on:
  push:
    branches:
    - publish
  page_build:
  workflow_dispatch:
jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node
      uses: actions/setup-node@v3
    - name: Install TypeScript
      run:  npm install typescript
    - name: Create build directory
      run: |
        mkdir ./build
        cp page.html ./build/index.html
    - name: Compile
      run: |
        tsc --project ./tsconfig.json \
          --sourceRoot null --sourceMap false
    - name: Upload
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./build
  deploy:
    name: Deploy to GitHub Pages
    needs: [build]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
