name: github-pages
on:
  push:
    branches:
    - publish
jobs:
  install_typescript:
    name: Install TypeScript
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - run: npm install typescript
  compile_project:
    name: Compile TypeScript files
    runs-on: ubuntu-latest
    needs: [install_typescript]
    steps:
    - run: tsc
