name: github-pages
on:
  push:
    branches:
    - publish
  page_build:
  workflow_dispatch:
jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node
      uses: actions/setup-node@v3
    - name: Install TypeScript
      run: |
        npm install typescript
        tsc --version
    - name: Create build directory
      run: |
        mkdir ./build ./build/assets
    - name: Copy static files
      run: |
        cp ./page.html ./build/index.html
        cp ./page.html ./build/10.html
        cp ./page.html ./build/100.html
        cp ./svg-override.css ./build/
    - name: Compile
      run: |
        tsc --project ./tsconfig.json \
          --sourceRoot null --sourceMap false
    - name: Get GitHub logo
      run: |
        wget https://github.githubassets.com/images/modules/logos_page/github-mark.zip &&
        unzip github-mark.zip github-mark/github-mark.svg &&
        mv ./github-mark/github-mark.svg -t ./build/assets/ || exit 0
    - name: Upload
      uses: actions/upload-pages-artifact@v1
      with:
        path: build
  deploy:
    name: Deploy to GitHub Pages
    needs: [build]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
